export const todoData = [
    {
        title: 'The first task title',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum quisquam iste molestiae quasi mollitia similique?',
        blue: true,
        red: true,
        purple: true,
        green: false,
        finished: false,
        id: 1,
        menu: false,
    },
    {
        title: 'The second task title',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum quisquam iste molestiae quasi mollitia similique? Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum quisquam iste molestiae quasi mollitia similique?',
        blue: false,
        red: false,
        purple: false,
        green: false,
        finished: false,
        id: 2,
        menu: false,
    },
    {
        title: 'The third task title',
        text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum quisquam iste molestiae quasi mollitia similique?',
        blue: false,
        red: true,
        purple: true,
        green: false,
        finished: false,
        id: 3,
        menu: false,
    },
]
